---
- hosts: 192.168.1.16
  tasks:
   - name: Check if PHP is installed
      register: php_installed
      command: php -v
      ignore_errors: true

   - name: This task is only executed if PHP is installed
     debug: var=php_install
     when: php_installed|success

   - name: This task is only executed if PHP is NOT installed
    debug: msg='PHP is NOT installed'
    when: php_installed|failed
  - name: Install PHP CLI
    become: true
    shell:  |
    yum-config-manager --enable remi-php72
    yum -y install php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysqlnd
    
