---
- hosts: 10.1.1.240
  tasks:
  
      
   gather_facts: False

  tasks:
   - name: Fetch Java version
     shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
     changed_when: False
     register: java_result
     
  - name: install java
      shell: |
       yum install java-1.8.0-openjdk -y
   - debug:
       msg: "{{ java_result.stdout }}"
